title: ZebrAI-Lab Documentation
description: Official Documentation of the ZebrAI-Lab Automation Tool
theme: just-the-docs

url: https://aizebra-lab.github.io/docs/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
